controllers:
  resource: ../src/Controller/
  type: attribute

pdf_show:
  path: /pdf/show/{filename}
  controller: App\Controller\QuizController::showPdf

app_register:
  path: /inscription
  controller: App\Controller\RegistrationController::register

evaluation_new:
  path: /evaluation/new
  controller: App\Controller\EvaluationController::new


